const ADD_TRAIT = "ADD_TRAIT";
const REMOVE_TRAIT = "REMOVE_TRAIT";
const RESET_TRAITS = "RESET_TRAITS";

const SET_IS_POSTING = "SET_IS_POSTING";
const SET_IS_FETCHING = "SET_IS_FETCHING";
const FETCH_USER = "FETCH_USER";
const LOGIN = "LOGIN";
const SIGNUP = "SIGNUP";
const LOGOUT = "LOGOUT";
const IS_FETCHING_ALL_TRAITS = "IS_FETCHING_ALL_TRAITS";
const FETCHED_ALL_TRAITS = "FETCHED_ALL_TRAITS";
const FETCHED_USER_TRAITS =  "FETCHED_USER_TRAITS";
const ADD_NOTE = "ADD_NOTE"
const REMOVE_NOTE = "REMOVE_NOTE";
const EDIT_NOTE = "EDIT_NOTE";
const IS_FETCHING_NOTES = "IS_FETCHING_NOTES";
const FETCHED_NOTES = "FETCHED_NOTES";
const IS_FETCHING_FOLDERS = "IS_FETCHING_FOLDERS";
const FETCHED_FOLDERS = "FETCHED_FOLDERS"
const SEARCH_NOTES = "SEARCH_NOTES"


export {
    ADD_TRAIT,
    REMOVE_TRAIT,
    RESET_TRAITS,
    SET_IS_POSTING,
    SET_IS_FETCHING,
    IS_FETCHING_ALL_TRAITS,
    FETCHED_USER_TRAITS,
    FETCHED_ALL_TRAITS,
    FETCH_USER,
    LOGIN,
    SIGNUP,
    LOGOUT,
    ADD_NOTE,
    REMOVE_NOTE,
    EDIT_NOTE,
    IS_FETCHING_NOTES,
    FETCHED_NOTES,
    IS_FETCHING_FOLDERS,
    FETCHED_FOLDERS,
    SEARCH_NOTES

};
